import {
  Heart,
  Brain,
  Stethoscope,
  Baby,
  Eye,
  Bone,
  Microscope,
  ShieldCheck,
  Scissors,
  Activity,
  Zap,
  Pill,
  Dna,
  Thermometer,
  UserPlus,
} from "lucide-react";

export const iconMap: { [key: string]: JSX.Element } = {
  Heart: <Heart className="h-6 w-6" />,
  Brain: <Brain className="h-6 w-6" />,
  Stethoscope: <Stethoscope className="h-6 w-6" />,
  Baby: <Baby className="h-6 w-6" />,
  Eye: <Eye className="h-6 w-6" />,
  Bone: <Bone className="h-6 w-6" />,
  Zap: <Zap className="h-6 w-6" />,
  Pill: <Pill className="h-6 w-6" />,
  Dna: <Dna className="h-6 w-6" />,
  Thermometer: <Thermometer className="h-6 w-6" />,
  UserPlus: <UserPlus className="h-6 w-6" />,
  Activity: <Activity className="h-6 w-6" />,
}; 